

export const resaults = {
    files: [
        {
            id: 1,
            username: 'mo.sa',
            name: 'file_1',
            size: 1522,
            mime_type: 'image/jpeg',
            extension: 'jpg',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 2,
            username: 'mo.sa',
            name: 'file_1',
            size: 1522,
            mime_type: 'image/jpeg',
            extension: 'jpg',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 3,
            username: 'mo.sa',
            name: 'file_1',
            size: 1522,
            mime_type: 'image/jpeg',
            extension: 'jpg',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 4,
            username: 'mo.sa',
            name: 'file_1',
            size: 1522,
            mime_type: 'image/jpeg',
            extension: 'jpg',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
    ],
    directories: [
        {
            id: 1,
            group_id: 1,
            name: 'folder_1',
            location: 'root',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 2,
            group_id: 1,
            name: 'folder_2',
            location: 'root',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 3,
            group_id: 1,
            name: 'folder_3',
            location: 'root',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
        {
            id: 4,
            group_id: 1,
            name: 'folder_4',
            location: 'root',
            created_at: Date.now(),
            updated_at: Date.now(),
        },
    ],
}